# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2017-09-30 18:10
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0006_auto_20170930_1108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='expiration_date',
            field=models.DateTimeField(default=datetime.datetime(
                                       2017, 9, 30, 18, 10, 40, 316864,
                                       tzinfo=utc)),
            preserve_default=False,
        ),
    ]
